[package]
name = "pgcli-rs"
version = "0.1.0"
authors = ["Jakub Wieczorek <jakub.adam.wieczorek@gmail.com>"]
edition = "2018"

[dependencies]
linefeed = "*"
matches = "*"
postgres = { git = "https://github.com/sfackler/rust-postgres.git" }
prettytable-rs = "*"
sqlparser = "*"
